### ISSUE TITLE
the server is already running

### ISSUE THREAD

**Issue by jongon** [php-kit/php-server#1]
On Windows i'm trying to run php-server start and i got this message: "the server is already running", and i have no started a server before,

**Comment by claudio-silva** [comment]
Are you using Git BASH or Cygwin?
The script requires **bash,** so it cannot run via `cmd.exe`.
What's your setup, so that I can replicate it for testing?

P.S. this is not well tested on windows, as on our company we all use Macs and Windows is not a priority for us. Nevertheless, it would be nice if it worked on windows too.

**Comment by jongon** [comment]
I'm using git bash,  i'm on Windows 10 x64 intel i7, 8GB, php 7.0.9, i'm running a simple php application with an index.php without any framework, i just wanted to test the server, i hope not to back to xampp :). this is a great tool for me on windows. i could use a docker container too but im not sharped with docker yet.

**Comment by claudio-silva** [comment]
Sorry for the delay, I have been very busy.
I have tested it on Windows 7 with Git 2.11 and it is working now.
